### ISSUE TITLE
Cannot change current user data

### ISSUE THREAD

**Issue by karelklima** [opendata-mvcr/sgov#11]
**Request: PUT /users/current**

I am trying to edit current user by sending the following payload to the endpoint above:
```json
{
  "firstName": "KarelX",
  "lastName": "KlimaX"
}
```

The server responds with **403** and following message:
`User User{Karel Klíma, username='karelklima@gmail.com'} attempted to update a different user's account.`

I am getting the same result in Mission Control as well as in Swagger.

The authorization token seems to be in order at the first glance, this is the decoded information:
```javascript
{
 sub: "karelklima@gmail.com",
 jti: "http://onto.fel.cvut.cz/ontologies/slovnik/agendovy/popis-dat/uživatel/karel-klima",
 iat: 1588799191,
 exp: 1588885591,
 role: "ROLE_USER-ROLE_ADMIN"
}
```

There is a fair chance that I am doing something wrong with the endpoint as the documentation is limited at this point. Please advice :-)

**Comment by psiotwo** [comment]
I have updated the Swagger docs for the endpoint. Also, as a by-product, fixed that the update put the data into the wrong context.

Please check.

**Comment by ledsoft** [comment]
I believe the problem is elsewhere - updates in TermIt (and thus in the Control Panel user management) are not PATCHes. That is, you have to provide the whole object for update, with both updated and original fields. The exception you are seeing is likely due to missing identifier in the provided update object.
The object for update should look as follows:
```JSON
{
  "uri": "http://example.org/your+uri",
  "firstName": "KarelX",
  "lastName": "KlimaX",
  "username": "your@username"
}
```

**Comment by karelklima** [comment]
This behavior is a bit weird, isn't it? The same endpoint is used for updating user password. In that case the request should contain also `originalPassword` and `passwordFields`. Which effectively means that some of the fields are mandatory, but it's definitely not like "you have to provide the whole object for update", as the endpoint clearly works without password data (which is good).

Ideally we should only send what data should be changed to the endpoint, and if that's necessary include also the URI, although that's redundant, since the username is already part of the authentication token. But why would we need to send both username and uri, that's a mystery to me.

**Comment by ledsoft** [comment]
Password is not sent, because it does not get to the client. Only in case of password update should it be a part of the request. This is an exception to the rule of always sending the complete update object to the backend (which holds everywhere in TermIt REST API) and it is an exception solely for security reasons.

As I said, patch updates are not currently implemented, because they would require determining the  changed attributes for every request.

**Comment by karelklima** [comment]
Alright, good to know that the passwords are the only exception. I'll adjust the code accordingly. Thanks!

**Comment by karelklima** [comment]
I still cannot get this to work. I'm now getting 500.

Payload:
```json
{
  "uri":"http://onto.fel.cvut.cz/ontologies/slovnik/agendovy/popis-dat/uživatel/karel-klima",
  "username":"karelklima@gmail.com",
  "firstName":"Karel",
  "lastName":"Klíma"
}
```

The edit call worked once. The payload for that call that worked was exactly what `GET /users/current` sends, with `firstName` and `lastName` properties changed. I noticed only afterwards that the GET data contain also `admin`, `password` and `persistenceContext` field as well. So I sent all of those as PUT and now it seems like the endpoint is broken.

This is what I receive now when trying to update my profile using the payload above:
```json
{
  "message": null,
  "messageId": null,
  "requestUri": "/sgov-server/users/current"
}
```

**Comment by psiotwo** [comment]
Fixed.

**Comment by karelklima** [comment]
I confirm it works.
